# Generated by Django 2.1.7 on 2019-05-17 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='next_lesson',
            new_name='lesson_next',
        ),
        migrations.RenameField(
            model_name='lessons',
            old_name='previous_lesson',
            new_name='lesson_previous',
        ),
    ]
